/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CICD_Test.app;

import CICD_Test.list.LinkedList;

import static CICD_Test.utilities.StringUtils.join;
import static CICD_Test.utilities.StringUtils.split;
import static CICD_Test.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
